### ISSUE TITLE
rfe_scan_range

### ISSUE THREAD

**Issue by AlibertJimmy** [RFExplorer/RFExplorer-IoT-for-Raspberry-Pi#1]
What is the unit of the frequency parameter ? 
It's write that it is in MHz but whenever I try to use the example : 
sudo ./rfe_scan_range /IOT  200 300 

I got the following error : 
ERROR: Start frequency is outside range!

The problem is that I'm using the RFE IoT Advanced 15-2700 MHz, so I'm in the frequency range.

**Comment by arocholl** [comment]
Hi, do you get any additional report traces so we can try to reproduce the problem here?
